"""
mailer.py — Build and send an HTML email with the top-scoring KYC job matches.

Constructs a readable, skimmable HTML email (with plain-text fallback) and
sends it via SMTP (STARTTLS) using the SMTP_* environment variables.
"""

from __future__ import annotations

import logging
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any, Dict, List

from config import EMAIL_TO, SMTP_HOST, SMTP_PASS, SMTP_PORT, SMTP_USER

logger = logging.getLogger(__name__)


def _build_html(matches: List[Dict[str, Any]]) -> str:
    """Build an HTML string for the email body."""
    today = date.today().isoformat()
    rows: List[str] = []

    for i, m in enumerate(matches, 1):
        job = m["job"]
        rating = m["rating"]
        score = rating["score"]
        verdict = rating["verdict"].upper()

        # Colour-code the score badge
        if score >= 85:
            badge_colour = "#2e7d32"  # dark green
        elif score >= 70:
            badge_colour = "#f57c00"  # orange
        else:
            badge_colour = "#c62828"  # red

        key_matches_html = "".join(
            f"<li>{km}</li>" for km in rating.get("key_matches", [])
        )
        gaps_html = "".join(f"<li>{g}</li>" for g in rating.get("gaps", []))

        rows.append(f"""
        <tr>
          <td style="padding:16px;border-bottom:1px solid #e0e0e0;">
            <div style="display:flex;align-items:center;gap:12px;margin-bottom:6px;">
              <span style="background:{badge_colour};color:#fff;padding:4px 10px;
                           border-radius:12px;font-size:13px;font-weight:600;">
                {score}/100
              </span>
              <span style="font-size:13px;color:#666;">{verdict}</span>
              <span style="font-size:12px;color:#999;">{rating.get('seniority_fit', '').upper()}</span>
            </div>
            <a href="{job['apply_link']}" style="font-size:16px;font-weight:600;
               color:#1565c0;text-decoration:none;">
              {job['title']} — {job['company']}
            </a>
            <div style="font-size:13px;color:#888;margin:4px 0;">
              {job['location']} &middot; {job.get('source', '')}
            </div>
            <p style="margin:8px 0 4px;color:#333;">{rating['reason']}</p>
            <div style="font-size:13px;margin:8px 0;">
              <a href="{job['apply_link']}" style="color:#1565c0;">Apply on Adzuna</a>
              &middot;
              <a href="{job.get('search_link', '#')}" style="color:#34a853;">Search Google</a>
            </div>
            <div style="font-size:13px;margin-top:8px;">
              <strong style="color:#2e7d32;">✓ Matches:</strong>
              <ul style="margin:2px 0 8px;padding-left:20px;">{key_matches_html}</ul>
              <strong style="color:#c62828;">⚠ Gaps:</strong>
              <ul style="margin:2px 0 0;padding-left:20px;">{gaps_html}</ul>
            </div>
          </td>
        </tr>
        """)

    return f"""\
<html>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
             max-width:700px;margin:0 auto;padding:20px;background:#fafafa;">
  <div style="background:#fff;border-radius:8px;box-shadow:0 1px 3px rgba(0,0,0,0.12);
              overflow:hidden;">
    <div style="background:#1a237e;color:#fff;padding:20px 24px;">
      <h1 style="margin:0;font-size:22px;">🔍 KYC Job Finder</h1>
      <p style="margin:4px 0 0;font-size:14px;opacity:0.85;">
        {len(matches)} new match{'es' if len(matches) != 1 else ''} — {today}
      </p>
    </div>
    <table style="width:100%;border-collapse:collapse;">
      {''.join(rows)}
    </table>
    <div style="padding:16px 24px;font-size:12px;color:#aaa;">
      Generated by kyc-job-finder. Scores are AI-estimated — always review the full JD.
    </div>
  </div>
</body>
</html>"""


def _build_plain(matches: List[Dict[str, Any]]) -> str:
    """Build a plain-text fallback for the email."""
    today = date.today().isoformat()
    lines = [f"KYC Job Finder — {len(matches)} new match(es) — {today}", "=" * 60]
    for i, m in enumerate(matches, 1):
        job = m["job"]
        rating = m["rating"]
        lines.append(
            f"\n{i}. [{rating['score']}/100] {job['title']} — {job['company']}"
        )
        lines.append(f"   {job['location']} | {job.get('source', '')}")
        lines.append(f"   Apply: {job['apply_link']}")
        search_link = job.get("search_link", "")
        if search_link:
            lines.append(f"   Search: {search_link}")
        lines.append(f"   {rating['reason']}")
        lines.append(f"   Matches: {', '.join(rating.get('key_matches', []))}")
        lines.append(f"   Gaps: {', '.join(rating.get('gaps', []))}")
    return "\n".join(lines)


def send_matches(matches: List[Dict[str, Any]]) -> None:
    """
    Build and send an email containing *matches*.

    Each element of *matches* should be a dict with keys ``job`` (the job dict)
    and ``rating`` (the rating dict from `rater.py`).
    """
    if not matches:
        logger.info("No matches to email — skipping.")
        return

    if not SMTP_PASS or not SMTP_USER:
        logger.warning("SMTP not configured — can't send email.")
        return

    today = date.today().isoformat()
    subject = f"{len(matches)} new KYC matches — {today}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = SMTP_USER
    msg["To"] = EMAIL_TO

    msg.attach(MIMEText(_build_plain(matches), "plain", "utf-8"))
    msg.attach(MIMEText(_build_html(matches), "html", "utf-8"))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            server.send_message(msg)
        logger.info("Email sent to %s with %d match(es)", EMAIL_TO, len(matches))
    except Exception:
        logger.exception("Failed to send email")